services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployments/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d marketplace"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1024M

  ads-service:
    build:
      context: ./services/ads-service
      dockerfile: Dockerfile
    container_name: ads-service
    environment:
      HTTP_ADDR: ":8081"
      POSTGRES_DSN: postgres://app:app@postgres:5432/marketplace?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8081/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 25s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  billing-service:
    build:
      context: ./services/billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    environment:
      HTTP_ADDR: ":8082"
      POSTGRES_DSN: postgres://app:app@postgres:5432/marketplace?sslmode=disable
      ADS_SERVICE_BASE_URL: http://ads-service:8081
    depends_on:
      postgres:
        condition: service_healthy
      ads-service:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8082/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 25s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

networks:
  app_net:
    name: marketplace_app_net

volumes:
  postgres_data:
