// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ads-service/internal/application/usecases"
	"ads-service/internal/infrastructure/adapters/postgres"
	"ads-service/internal/presentation/http"
	"net/http"
)

// Injectors from wire.go:

func InitializeHTTPHandler() (http.Handler, error) {
	db, err := postgres.OpenDB()
	if err != nil {
		return nil, err
	}
	adsRepository, err := postgres.NewAdsRepository(db)
	if err != nil {
		return nil, err
	}
	createAdUseCase, err := usecases.NewCreateAdUseCase(adsRepository)
	if err != nil {
		return nil, err
	}
	publishAdUseCase, err := usecases.NewPublishAdUseCase(adsRepository)
	if err != nil {
		return nil, err
	}
	getAdUseCase, err := usecases.NewGetAdUseCase(adsRepository)
	if err != nil {
		return nil, err
	}
	handler := httpapi.NewRouter(createAdUseCase, publishAdUseCase, getAdUseCase, db)
	return handler, nil
}
