// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"billing-service/internal/application/usecases"
	"billing-service/internal/infrastructure/adapters/http"
	"billing-service/internal/infrastructure/adapters/postgres"
	"billing-service/internal/presentation/http"
	"net/http"
)

// Injectors from wire.go:

func InitializeHTTPHandler() (http.Handler, error) {
	client := provideHTTPClient()
	adsCatalogAdapter, err := httpadapter.NewAdsCatalogAdapter(client)
	if err != nil {
		return nil, err
	}
	db, err := postgres.OpenDB()
	if err != nil {
		return nil, err
	}
	promotionsRepository, err := postgres.NewPromotionsRepository(db)
	if err != nil {
		return nil, err
	}
	purchasePromotionUseCase, err := usecases.NewPurchasePromotionUseCase(adsCatalogAdapter, promotionsRepository)
	if err != nil {
		return nil, err
	}
	handler := httpapi.NewRouter(purchasePromotionUseCase, db)
	return handler, nil
}
